"""empty message

Revision ID: 410ebcde3b5f
Revises: f0bade08e651
Create Date: 2024-09-03 19:53:35.031594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410ebcde3b5f'
down_revision = 'f0bade08e651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prueba')
    # ### end Alembic commands ###
